### ISSUE TITLE
How to prepare custom data in .tsv file for training and inference?

### ISSUE THREAD

**Issue by GenTxt** [ucfnlp/sent-fusion-transformers#3]
Have everything working but was wondering how to prepare custom text file data in .tsv so that it follows same format as 'input_decoding_pocd' etc.

Can you provide a python script that prepares similar data?

Also, the paper sentence example 'Allan Donald served as South Africa bowling coach since 2011.' is sentence-case.
Was a Bert-cased model used?

Cheers

**Comment by loganlebanoff** [comment]
I do not have a python script ready to easily generate the data. Here is the procedure I used:

1. Generate singletons/pairs data using the procedure outlined here: https://github.com/ucfnlp/summarization-sing-pair-mix
2. Filter the data to use only the pairs of sentences (along with the corresponding output fusion sentence)
3. Run spacy coreference resolution model on the pairs of sentences for each instance
4. Filter the data to use only the instances where an entity is shared between the pair of sentences

No, bert-base was used. The sentences are all lowercased before being input to the model.
